### ISSUE TITLE
How to retrieve the scan report 

### ISSUE THREAD

**Issue by gautam-shipt** [checkmarx-ts/checkmarx-cxflow-github-action#18]
We are using this to integrate with our github action pipeline . 
We want to extract the scan report and post a summary to one of the slack channel 
How do we retrieve the scan report ?

**Comment by MithileshPawar** [comment]
Hi @gautam-shipt ,

You can generate a csv report mentioning it as the bug-tracker along with its own config options.

For example, the simplest way to generate the csv report would be using the following params.

In your github action yml file, just add the following lines :
```
bug_tracker: Csv
params: --csv.file-name-format=[TEAM]-[PROJECT].csv --csv.include-header=true --csv.data-folder=/myCSV
```

That's it, this should allow you to generate the cxv file.

Few things to note:
* The option '--csv.data-folder=./myCSV' is not mandatory. And If it is absent the cxv file will be generated in '/tmp' folder.
* The name of the csv can be modified using the options mentioned in this link : https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#csv
