### ISSUE TITLE
Feature Request: Support for CxSAST token authentication

### ISSUE THREAD

**Issue by ebickle** [checkmarx-ts/checkmarx-cxflow-github-action#21]
Our team is looking at migrating from the existing `checkmarx-github-action` and ran into an issue with this action due to it's lack of token-based authentication.

All of our users authenticate with Checkmarx using their Active Directory personal user accounts. We cannot use these accounts for Checkmarx authentication within a GitHub Action (or any other CI/CD environment) since it would give multiple people access to a personal AD account and would expose their sensitive password - this is strictly prohibited by our corporate security policy and annual compliance training.

Adding support for token authentication would allow us to authenticate directly to CxSAST from GitHub actions without exposing the user's password.

**Comment by jbrotsos** [comment]
Hey @ebickle 

This is a limitation with our current CxSAST manager (9.x).  We suggest instead of using an AD account to create a local account on Checkmarx (i.e. sast-scanner).

In our next generation platform, you can use token based authentication.

Sorry and thanks,
James

**Comment by ebickle** [comment]
Username and password authentication via a local account worked well, thanks!
