### ISSUE TITLE
Feature: Async call

### ISSUE THREAD

**Issue by sergioissi** [checkmarx-ts/checkmarx-cxflow-github-action#24]
Hello,
in the documentation I don't seem to have found the possibility to make an asynchronous call to the server through the Github Action. I have a repository with many lines of code and a full scan takes me hours, would it be possible to make the call to the server without having to wait for the response?

Thanks
Sergio

**Comment by jbrotsos** [comment]
Hey @sergioissi 

https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#none--wait

Change the bug_tracker to NONE.

**Comment by sergioissi** [comment]
thank you, this is exactly what I need.

**Comment by arpitjindal97** [comment]
How to do Full scan ? I have tried multiple times and it always comment `Attempt to perform scan on 8/21/2021 4:24:47 PM - No code changes were detected; CxFlow Automated Scan`
I have set incremental `false` also.

The Sarif report which is being generated is also empty. I'm guessing incremental scan might be causing this behaviour

**Comment by satyamchaurasiapersistent** [comment]
@arpitjindal97 you can pass --checkmarx.incremental=true in params.
