### ISSUE TITLE
Not able to logged in our company hosted checkmarx with credentials 

### ISSUE THREAD

**Issue by diptilenka** [checkmarx-ts/checkmarx-cxflow-github-action#25]
While running the github action for the checkmarx,
the error am getting while acccesing the Checkmarx URl hosted in my organisation i.e "Name does not resolve; nested exception is java.net.UnknownHostException: " .

How can it be resolved?

my repo link

https://github.com/diptilenka/dipti-am-heart.git

**Comment by jbrotsos** [comment]
Hello @diptilenka,

Where did you get those variable names from?

Can you use the ones as defined in the README?  https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

Also, can GH access that Checkmarx Server?  I was unable to (https://srv-cxsuite.onbase.net/).

Thanks,
James

**Comment by diptilenka** [comment]
@jbrotsos  
Now i created a self runner machine with windows x 64.
While running by the action the logs are "Container action is only supported on Linux" error.
<img width="1060" alt="Screenshot 2021-07-02 at 3 05 31 PM" src="https://user-images.githubusercontent.com/63293480/124254747-ffc18b80-db46-11eb-874a-83189cab337e.png">

**Comment by diptilenka** [comment]
Created a self runner and installed the organisational certificate inside that docker
