### ISSUE TITLE
How to retrieve the scan report using pdf to post in an email with attachments as pdf reports

### ISSUE THREAD

**Issue by diptilenka** [checkmarx-ts/checkmarx-cxflow-github-action#27]
How to retrieve the scan report using pdf to post in an email with attachments as pdf reports

**Comment by naruto3co** [comment]
i dont know . I also have the problem of not being able to export the report file as pdf

**Comment by satyamchaurasiapersistent** [comment]
Please follow this link to generate PDF report. : https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#pdf
