### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by arpitjindal97** [checkmarx-ts/checkmarx-cxflow-github-action#28]
Checkmarx is hosted inside the company's Infra with Self-Signed certificates. This action doesn't provide any way to inject certs.

**Comment by brentVilla** [comment]
Is this the type of error you're seeing?

`org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://*******/cxrestapi/auth/identity/connect/token": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by arpitjindal97** [comment]
I don't have the exact logs for it but your logs seems related

**Comment by arpitjindal97** [comment]
Right now, I'm using a hack to use this action and make it compatible with self-signed checkmarx
```
steps:
      - name: Checkout Stage
        uses: actions/checkout@v2

      - name: Build checkmarx image
        run: |
          apt update -qq && apt-get install git -y > /dev/null
          mkdir _tmp && cd _tmp
          git clone https://github.com/checkmarx-ts/checkmarx-cxflow-github-action
          cd checkmarx-cxflow-github-action
          JAVA_LINE=`tail -n 1 entrypoint.sh`
          cat > entrypoint.sh<< EOF
          #!/bin/sh
          wget http://example.com/path/to/root.crt -O "Root.crt"
          keytool -trustcacerts -importcert -alias TLS1 -file "Root.crt" -keystore "/etc/ssl/certs/java/cacerts" -storepass 'changeit' -noprompt
          rm Root.crt
          $JAVA_LINE
          EOF
      - name: Checkmarx CxFlow Action
        uses: ./_tmp/checkmarx-cxflow-github-action
        with:
          project: SAMPLE_PROJECT
          team: "/CxServer/Path/to/team"
          checkmarx_url: https://xxxxx
          checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          bug_tracker: Sarif
          params: "--checkmarx.version=9.0"
```

**Comment by ddhawal** [comment]
> Is this the type of error you're seeing?
> 
> `org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://*******/cxrestapi/auth/identity/connect/token": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Do we have any resolution to this?
