### ISSUE TITLE
How to scan generated code by a GitHub action?

### ISSUE THREAD

**Issue by joerghartmann** [checkmarx-ts/checkmarx-cxflow-github-action#40]
Hi experts, 

we do have a GitHub CD workflow which generates source code. 

The workflow checks out the repository and generates source code for Java. The source code itself is uploaded via the `actions/upload-artifact@v2` action. Note that the generated code is not part of the repository and thus not committed.

If I understood the checkmarx action correctly, it's only possible to scan the source in the repository itself, isn't it?

We'll like to scan the generated code created by our CD workflow. Is there any configuration option to achieve this goal?

**Comment by jbrotsos** [comment]
Hey @joerghartmann ,

The Cx scan actually will scan anything in the root directory, not necessarily the repository.  So if you have generated code, make sure it is done before scanning with Checkmarx.

James
