### ISSUE TITLE
GitHub action fails if repo contains application.xml file

### ISSUE THREAD

**Issue by james-bostock-cx** [checkmarx-ts/checkmarx-cxflow-github-action#43]
The CxFlow GitHub action will fail if the repository contains a file named `application.xml` in its root directory. This is because the Spring framework tries to load it as a configuration file.

I have created a sample repository that exhibits this problem: https://github.com/james-bostock-cx/cx-flow-github-action-application-xml

See also [CxFlow issue #993](https://github.com/checkmarx-ltd/cx-flow/issues/993) which is for the same issue but with the GitLab CI/CD template.

**Comment by satyamchaurasiapersistent** [comment]
Please refer FAQ in cxflow wilki we have mentioned how to resolve this issue.
