### ISSUE TITLE
Jira Service - "Resolution is required."

### ISSUE THREAD

**Issue by bfentiman-ipipeline** [checkmarx-ts/checkmarx-cxflow-github-action#46]
While attempting to transition a Jira ticket to Closed, the GitHub action is running into the error:
```
com.atlassian.jira.rest.client.api.RestClientException: [ErrorCollection{status=400, errors={}, errorMessages=[Field Resolution is required.]}]
```
As "Resolution" is one of the default fields for Jira, I'm looking at getting that automatically set so that this error doesn't occur anymore.

**Comment by jbrotsos** [comment]
@bfentiman-ipipeline are you using config-as-code file to do your Jira settings?

https://github.com/checkmarx-ltd/cx-flow/wiki/Config-As-Code#current-overrides-available

For custom Jira integration, it is recommended to use professional services to help.
