### ISSUE TITLE
SCA scans on a PR that find vulnerabilities don't block.

### ISSUE THREAD

**Issue by rs-garrick** [checkmarx-ts/checkmarx-cxflow-github-action#53]
Using `break_build: true` and `bug_tracker: GITHUBPULL`.  SAST scans correctly block the PR, but SCA scans don't.  Is this expected?

**Comment by satyamchaurasiapersistent** [comment]
SCA is having different thresholds you need to specifically define for SCA https://github.com/checkmarx-ltd/cx-flow/wiki/CxSCA-Integration 
![image](https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/assets/102941840/46016018-6bb5-4d09-bf7e-91e1254f39a2)
