### ISSUE TITLE
CxGo scan showing misleading hints

### ISSUE THREAD

**Issue by kollol2k** [checkmarx-ts/checkmarx-cxflow-github-action#6]
When team is not configured based on correct semantics, we get the errors below.

**com.checkmarx.sdk.exception.CheckmarxException: Parent team could not be established. Please ensure correct team is provided.
Some hints:
	- team name is case-sensitive
	- trailing slash is not allowed
	_**- team name separator depends on Checkmarx product version specified in CxFlow configuration:
		Checkmarx version: 8.9**_
		Separator that should be used: \

	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determineTeamAndOwnerID(ScanRequestConverter.java:114)
	at com.checkmarx.flow.service.SastScanner.executeCxScan(SastScanner.java:182)**

Since this is a CxGo scan, "Checkmarx version: 8.9" is irrelevant here and the line above saying it depends on the product version.

**Comment by kmcdon83** [comment]
FYI @kollol2k - transferring to CxFlow:
https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/issues/6
