### ISSUE TITLE
[Question] get project id url from action as output

### ISSUE THREAD

**Issue by dtcMLOps** [checkmarx-ts/checkmarx-cxflow-github-action#60]
Hi folks,

Greetings.

I was wondering if there is a way to get the project ID in order to construct the url as follows:

![Screenshot from 2023-02-27 11-17-34](https://user-images.githubusercontent.com/115469901/221619159-ca5be921-c151-4d93-8307-04dfc8ce6533.png)

Or, if there is a way to get that url printed as PR comment when running the action in a workflow.

**Comment by mark-strasser-nnl** [comment]
@dtcMLOps  There is a way to parse the scan ID from the output, I assume it's the same for project ID.  

https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#outputscanid
