### ISSUE TITLE
Action logs Satyam in the scan output

### ISSUE THREAD

**Issue by raoganeshr** [checkmarx-ts/checkmarx-cxflow-github-action#65]
If you see the scan output, you will see Satyam next to the project ID

`can created with Id 1213648 for project Id Satyam 12722`

I believe this was added by mistake by @satyamchaurasiapersistent for debugging. I am using v1.6 of the action

**Comment by mark-strasser-nnl** [comment]
@satyamchaurasiapersistent  this can be closed out, was fixed in the mentioned PR
