### ISSUE TITLE
Pin version of cx-flow version each release

### ISSUE THREAD

**Issue by macox** [checkmarx-ts/checkmarx-cxflow-github-action#75]
Would it be possible to pin the version of the checkmarx/cx-flow base image used for each version of this GH action?

Having pinned the version of this action within a workflow the underlying cx-flow version can still change unknowingly, and break unexpectedly, as was experienced recently.

**Comment by satyamchaurasiapersistent** [comment]
You can do the same by forking this repo and point to any version of cxflow instead of using new version
you can make changes in docker file as shown below
![image](https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/assets/102941840/2665b2c2-7e5a-406f-8ea8-642540179009)
