### ISSUE TITLE
How to generate report as pdf format

### ISSUE THREAD

**Issue by simhan95** [checkmarx-ts/checkmarx-cxflow-github-action#76]
I use this action checkmarx-ts/checkmarx-cxflow-github-action@v1.9 and can only generate report in either sarif or git issues etc. Cannot able to generate report in pdf format. How to do that ?

**Comment by satyamchaurasiapersistent** [comment]
Please refer this link : https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#pdf
