### ISSUE TITLE
[Enhancement request] possibility to have "checkmarx-cxflow-gitlab"

### ISSUE THREAD

**Issue by KafkaProServerless** [checkmarx-ts/checkmarx-cxflow-github-action#77]
Hello team,

Just wanted to reach out with a small enhancement request.

Would it be possible to have a GitLab equivalent, something like "checkmarx-cxflow-gitlab"

Which can take care of CxFlow integration with Gitlab issues, merge requests, commits, and security dashboard?

Thank you

**Comment by satyamchaurasiapersistent** [comment]
We are already supporting GitLab as well for more details please refer : https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#gitlab
