### ISSUE TITLE
Feature Request: Optional Parameter to Reduce Email Notifications for Checkmarx Scan Comments

### ISSUE THREAD

**Issue by leinardi** [checkmarx-ts/checkmarx-cxflow-github-action#78]
# Description
To minimize unnecessary email notifications sent to all subscribers of a Pull Request, it would be beneficial to introduce an optional parameter that can:

~~1. Suppress the generation of the "Scan submitted to Checkmarx" comment.~~ (can be already achieved with  `--github.ScanSubmittedComment=false`)
2. Prevent the creation of the "Scan Summary & Details" comment when no violations are found.

# Current Behavior:
Under the current implementation, two emails are sent each time these comments are created by the Action, regardless of whether any action is required. This results in redundant notifications that clutter the inboxes of PR subscribers.

# Proposed Solution:
Add an optional parameter to control the generation of these comments, thereby reducing unnecessary email notifications and improving the user experience.

Thank you for considering this enhancement.

**Comment by richard-grainger-veeva** [comment]
You can already prevent "scan submitted" noise on Github PRs with parameter `--github.ScanSubmittedComment=false` added to `params` (1 above).  What we need is 2: "Prevent the creation of the "Scan Summary & Details" comment when no violations are found."

Thanks!

**Comment by satyamchaurasiapersistent** [comment]
Please use --github.ScanSubmittedComment=false to turnoff comments.

**Comment by leinardi** [comment]
Hi @satyamchaurasiapersistent, as @richard-grainger-veeva explained, that is addressing only half of the issue (suppressing the "Scan submitted to Checkmarx" comment): we still need to have a way to:

> 2. Prevent the creation of the "Scan Summary & Details" comment when no violations are found.

@satyamchaurasiapersistent can you please re-open the issue?

**Comment by richard-grainger-veeva** [comment]
@satyamchaurasiapersistent

Yes, this is not resolved. Please re-open!

**Comment by leinardi** [comment]
I have created #79 to address the point number 2 specifically.
